version: "3.7"

services:
  db:
    image: postgres:15.1-alpine3.16
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: app
    healthcheck:
      test: ["CMD", "pg_isready", "--host=db", "--user=postgres"]
      interval: 100ms
      retries: 100
      timeout: 10s
  app:
    build:
      context: .
    stdin_open: true
    tty: true
    init: true
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/opt/app
    tmpfs:
      - /opt/app/tmp/cache
      - /opt/app/tmp/pids
      - /opt/app/tmp/sockets
    environment:
      DB_DATABASENAME: app
      DB_HOST: db
      RAILS_SERVE_STATIC_FILES: 1
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
    driver: local
